import {
  Award,
  Banknote,
  Baby,
  Bolt,
  BookOpen,
  Briefcase,
  Building2,
  Bus,
  Car,
  CircleDollarSign,
  Clapperboard,
  CreditCard,
  Dumbbell,
  Film,
  Fuel,
  Gift,
  GraduationCap,
  HandCoins,
  Heart,
  HeartPulse,
  Home,
  Landmark,
  Laptop,
  Leaf,
  type LucideIcon,
  Percent,
  PawPrint,
  PiggyBank,
  Plane,
  Receipt,
  RotateCcw,
  Scissors,
  Shield,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Sparkles,
  Stethoscope,
  Target,
  Ticket,
  TrendingUp,
  Tv,
  Users,
  Utensils,
  Wallet,
  Wifi,
  Zap,
} from "lucide-react";

// Curated icon set for accounts, categories, budgets, savings goals, and
// payment methods. Keys are the kebab-case names stored in the DB.
const FINANCE_ICON_MAP: Record<string, LucideIcon> = {
  // generic / money
  circle: CircleDollarSign,
  wallet: Wallet,
  "piggy-bank": PiggyBank,
  banknote: Banknote,
  "credit-card": CreditCard,
  landmark: Landmark,
  receipt: Receipt,
  "circle-dollar-sign": CircleDollarSign,
  coins: HandCoins,
  // income
  briefcase: Briefcase,
  laptop: Laptop,
  "trending-up": TrendingUp,
  percent: Percent,
  award: Award,
  gift: Gift,
  "rotate-ccw": RotateCcw,
  building: Building2,
  sparkles: Sparkles,
  // expense
  utensils: Utensils,
  "shopping-cart": ShoppingCart,
  home: Home,
  zap: Zap,
  bus: Bus,
  car: Car,
  stethoscope: Stethoscope,
  "heart-pulse": HeartPulse,
  "graduation-cap": GraduationCap,
  film: Film,
  clapperboard: Clapperboard,
  "shopping-bag": ShoppingBag,
  tv: Tv,
  wifi: Wifi,
  plane: Plane,
  smartphone: Smartphone,
  users: Users,
  "paw-print": PawPrint,
  shield: Shield,
  scissors: Scissors,
  dumbbell: Dumbbell,
  baby: Baby,
  leaf: Leaf,
  fuel: Fuel,
  ticket: Ticket,
  heart: Heart,
  bolt: Bolt,
  target: Target,
  book: BookOpen,
};

/** Ordered icon names for the picker UI. */
export const FINANCE_ICON_NAMES: readonly string[] = Object.keys(FINANCE_ICON_MAP);

export function getFinanceIcon(name: string): LucideIcon {
  return FINANCE_ICON_MAP[name] ?? CircleDollarSign;
}
